import{a as d}from"./assets/vendor-0cb09735.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const g=document.querySelector(".list-one");d.get("https://books-backend.p.goit.global/books/top-books").then(t=>f(t.data)).catch(t=>console.log(t.message));function f(t){let s="",n="";for(let r in t){s+=`
            <li class="books_list">
                <h3 class="name_category">${t[r].list_name}</h3>
                <ul class="images_books"></ul>
            </li>`;for(let e in t[r].books)n+=`<li class="image_book"><img src="${t[r].books[e].book_image}"></img></li>`}g.insertAdjacentHTML("beforeend",s),g.insertAdjacentHTML("beforeend",n)}const u=document.querySelector(".list-one"),m=document.querySelector(".list_categories"),l=document.querySelector(".main-title");let c;function p(t){let s="";t.forEach(r=>{s+=`<li tabindex="0" class="categoria">${r.list_name}</li>`}),m.insertAdjacentHTML("beforeend",s),document.querySelectorAll(".categoria").forEach(r=>{r.addEventListener("click",e=>{e.preventDefault(),e.target.textContent!=="All categories"?l.textContent=e.target.textContent:l.textContent="Best Sellers Books";const o=l.textContent.split(" "),i=o[o.length-1];l.innerHTML=l.innerHTML.replace(i,`<span class="blue">${i}</span>`),c=e.target.textContent,c=c.replace(/ /g,"%20"),d.get(`https://books-backend.p.goit.global/books/category?category=${c}`).then(a=>b(a.data)).catch(a=>console.log(a.message))})})}d.get("https://books-backend.p.goit.global/books/category-list").then(t=>{p(t.data)}).catch(t=>console.log(t.message));async function b(t){let s="";u.innerHTML="",t.forEach(n=>{s+=`<li class="book">
                        <img class="img-example" src="${n.book_image}"></img>
                            <div class="box-cards">
                                <p class="title-book">${n.title}</p>
                                <p class="author-book">${n.author}</p>
                            </div>
                      </li>`}),u.insertAdjacentHTML("beforeend",s)}
//# sourceMappingURL=commonHelpers.js.map
